import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import SupabaseAuthProvider from "@/components/providers/AuthProvider";
import "./globals.css";

const roboto = Roboto({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "App name",
  description: "Generated by create next app",
  themeColor: "black",
  referrer: "origin-when-cross-origin",
  colorScheme: "dark",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={roboto.className}>
        <SupabaseAuthProvider>{children}</SupabaseAuthProvider>
      </body>
    </html>
  );
}
